// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/contracts/admin.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminDashboardConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutePrefix   string                 `protobuf:"bytes,1,opt,name=route_prefix,json=routePrefix,proto3" json:"route_prefix,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	TargetApp     string                 `protobuf:"bytes,3,opt,name=target_app,json=targetApp,proto3" json:"target_app,omitempty"`
	AuthModule    string                 `protobuf:"bytes,4,opt,name=auth_module,json=authModule,proto3" json:"auth_module,omitempty"`
	AuthzModule   string                 `protobuf:"bytes,5,opt,name=authz_module,json=authzModule,proto3" json:"authz_module,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	AssetRoot     string                 `protobuf:"bytes,7,opt,name=asset_root,json=assetRoot,proto3" json:"asset_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDashboardConfig) Reset() {
	*x = AdminDashboardConfig{}
	mi := &file_internal_contracts_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDashboardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDashboardConfig) ProtoMessage() {}

func (x *AdminDashboardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDashboardConfig.ProtoReflect.Descriptor instead.
func (*AdminDashboardConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminDashboardConfig) GetRoutePrefix() string {
	if x != nil {
		return x.RoutePrefix
	}
	return ""
}

func (x *AdminDashboardConfig) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AdminDashboardConfig) GetTargetApp() string {
	if x != nil {
		return x.TargetApp
	}
	return ""
}

func (x *AdminDashboardConfig) GetAuthModule() string {
	if x != nil {
		return x.AuthModule
	}
	return ""
}

func (x *AdminDashboardConfig) GetAuthzModule() string {
	if x != nil {
		return x.AuthzModule
	}
	return ""
}

func (x *AdminDashboardConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AdminDashboardConfig) GetAssetRoot() string {
	if x != nil {
		return x.AssetRoot
	}
	return ""
}

type AdminStepConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStepConfig) Reset() {
	*x = AdminStepConfig{}
	mi := &file_internal_contracts_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStepConfig) ProtoMessage() {}

func (x *AdminStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStepConfig.ProtoReflect.Descriptor instead.
func (*AdminStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminStepConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type AdminPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermission) Reset() {
	*x = AdminPermission{}
	mi := &file_internal_contracts_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermission) ProtoMessage() {}

func (x *AdminPermission) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermission.ProtoReflect.Descriptor instead.
func (*AdminPermission) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminPermission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AdminPermission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AdminPermission) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type AdminContextSelector struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SelectedContextKey  string                 `protobuf:"bytes,1,opt,name=selected_context_key,json=selectedContextKey,proto3" json:"selected_context_key,omitempty"`
	AllowedContextKinds []string               `protobuf:"bytes,2,rep,name=allowed_context_kinds,json=allowedContextKinds,proto3" json:"allowed_context_kinds,omitempty"`
	LaunchUrl           string                 `protobuf:"bytes,3,opt,name=launch_url,json=launchUrl,proto3" json:"launch_url,omitempty"`
	SwitchPermissions   []*AdminPermission     `protobuf:"bytes,4,rep,name=switch_permissions,json=switchPermissions,proto3" json:"switch_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminContextSelector) Reset() {
	*x = AdminContextSelector{}
	mi := &file_internal_contracts_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminContextSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminContextSelector) ProtoMessage() {}

func (x *AdminContextSelector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminContextSelector.ProtoReflect.Descriptor instead.
func (*AdminContextSelector) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminContextSelector) GetSelectedContextKey() string {
	if x != nil {
		return x.SelectedContextKey
	}
	return ""
}

func (x *AdminContextSelector) GetAllowedContextKinds() []string {
	if x != nil {
		return x.AllowedContextKinds
	}
	return nil
}

func (x *AdminContextSelector) GetLaunchUrl() string {
	if x != nil {
		return x.LaunchUrl
	}
	return ""
}

func (x *AdminContextSelector) GetSwitchPermissions() []*AdminPermission {
	if x != nil {
		return x.SwitchPermissions
	}
	return nil
}

type AdminContribution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Path            string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	RenderMode      string                 `protobuf:"bytes,5,opt,name=render_mode,json=renderMode,proto3" json:"render_mode,omitempty"`
	AppContext      string                 `protobuf:"bytes,6,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	Permissions     []*AdminPermission     `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Actions         []string               `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	ContextSelector *AdminContextSelector  `protobuf:"bytes,10,opt,name=context_selector,json=contextSelector,proto3" json:"context_selector,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminContribution) Reset() {
	*x = AdminContribution{}
	mi := &file_internal_contracts_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminContribution) ProtoMessage() {}

func (x *AdminContribution) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminContribution.ProtoReflect.Descriptor instead.
func (*AdminContribution) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminContribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminContribution) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminContribution) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AdminContribution) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AdminContribution) GetRenderMode() string {
	if x != nil {
		return x.RenderMode
	}
	return ""
}

func (x *AdminContribution) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *AdminContribution) GetPermissions() []*AdminPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdminContribution) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AdminContribution) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AdminContribution) GetContextSelector() *AdminContextSelector {
	if x != nil {
		return x.ContextSelector
	}
	return nil
}

type RegisterContributionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Contribution  *AdminContribution     `protobuf:"bytes,2,opt,name=contribution,proto3" json:"contribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContributionInput) Reset() {
	*x = RegisterContributionInput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContributionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContributionInput) ProtoMessage() {}

func (x *RegisterContributionInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContributionInput.ProtoReflect.Descriptor instead.
func (*RegisterContributionInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterContributionInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RegisterContributionInput) GetContribution() *AdminContribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

type RegisterContributionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	Contribution  *AdminContribution     `protobuf:"bytes,2,opt,name=contribution,proto3" json:"contribution,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContributionOutput) Reset() {
	*x = RegisterContributionOutput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContributionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContributionOutput) ProtoMessage() {}

func (x *RegisterContributionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContributionOutput.ProtoReflect.Descriptor instead.
func (*RegisterContributionOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterContributionOutput) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *RegisterContributionOutput) GetContribution() *AdminContribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

func (x *RegisterContributionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListContributionsInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Module              string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	AppContext          string                 `protobuf:"bytes,2,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	GrantedPermissions  []string               `protobuf:"bytes,3,rep,name=granted_permissions,json=grantedPermissions,proto3" json:"granted_permissions,omitempty"`
	SelectedContextKind string                 `protobuf:"bytes,4,opt,name=selected_context_kind,json=selectedContextKind,proto3" json:"selected_context_kind,omitempty"`
	SelectedContextId   string                 `protobuf:"bytes,5,opt,name=selected_context_id,json=selectedContextId,proto3" json:"selected_context_id,omitempty"`
	ContextAuthorized   bool                   `protobuf:"varint,6,opt,name=context_authorized,json=contextAuthorized,proto3" json:"context_authorized,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListContributionsInput) Reset() {
	*x = ListContributionsInput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContributionsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContributionsInput) ProtoMessage() {}

func (x *ListContributionsInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContributionsInput.ProtoReflect.Descriptor instead.
func (*ListContributionsInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListContributionsInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ListContributionsInput) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *ListContributionsInput) GetGrantedPermissions() []string {
	if x != nil {
		return x.GrantedPermissions
	}
	return nil
}

func (x *ListContributionsInput) GetSelectedContextKind() string {
	if x != nil {
		return x.SelectedContextKind
	}
	return ""
}

func (x *ListContributionsInput) GetSelectedContextId() string {
	if x != nil {
		return x.SelectedContextId
	}
	return ""
}

func (x *ListContributionsInput) GetContextAuthorized() bool {
	if x != nil {
		return x.ContextAuthorized
	}
	return false
}

type ListContributionsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contributions []*AdminContribution   `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContributionsOutput) Reset() {
	*x = ListContributionsOutput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContributionsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContributionsOutput) ProtoMessage() {}

func (x *ListContributionsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContributionsOutput.ProtoReflect.Descriptor instead.
func (*ListContributionsOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListContributionsOutput) GetContributions() []*AdminContribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

func (x *ListContributionsOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuthorizeAdminActionInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Module             string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Subject            string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource           string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action             string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	AppContext         string                 `protobuf:"bytes,5,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	AuthzChecked       bool                   `protobuf:"varint,6,opt,name=authz_checked,json=authzChecked,proto3" json:"authz_checked,omitempty"`
	AuthzAllowed       bool                   `protobuf:"varint,7,opt,name=authz_allowed,json=authzAllowed,proto3" json:"authz_allowed,omitempty"`
	GrantedPermissions []string               `protobuf:"bytes,8,rep,name=granted_permissions,json=grantedPermissions,proto3" json:"granted_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthorizeAdminActionInput) Reset() {
	*x = AuthorizeAdminActionInput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeAdminActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeAdminActionInput) ProtoMessage() {}

func (x *AuthorizeAdminActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeAdminActionInput.ProtoReflect.Descriptor instead.
func (*AuthorizeAdminActionInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorizeAdminActionInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *AuthorizeAdminActionInput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizeAdminActionInput) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeAdminActionInput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthorizeAdminActionInput) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *AuthorizeAdminActionInput) GetAuthzChecked() bool {
	if x != nil {
		return x.AuthzChecked
	}
	return false
}

func (x *AuthorizeAdminActionInput) GetAuthzAllowed() bool {
	if x != nil {
		return x.AuthzAllowed
	}
	return false
}

func (x *AuthorizeAdminActionInput) GetGrantedPermissions() []string {
	if x != nil {
		return x.GrantedPermissions
	}
	return nil
}

type AuthorizeAdminActionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeAdminActionOutput) Reset() {
	*x = AuthorizeAdminActionOutput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeAdminActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeAdminActionOutput) ProtoMessage() {}

func (x *AuthorizeAdminActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeAdminActionOutput.ProtoReflect.Descriptor instead.
func (*AuthorizeAdminActionOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AuthorizeAdminActionOutput) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizeAdminActionOutput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorizeAdminActionOutput) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeAdminActionOutput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthorizeAdminActionOutput) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthorizeAdminActionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminResourceActionInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Module         string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	ContributionId string                 `protobuf:"bytes,2,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	Resource       string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action         string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Subject        string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	AppContext     string                 `protobuf:"bytes,6,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	AuthzChecked   bool                   `protobuf:"varint,7,opt,name=authz_checked,json=authzChecked,proto3" json:"authz_checked,omitempty"`
	AuthzAllowed   bool                   `protobuf:"varint,8,opt,name=authz_allowed,json=authzAllowed,proto3" json:"authz_allowed,omitempty"`
	Payload        *structpb.Struct       `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminResourceActionInput) Reset() {
	*x = AdminResourceActionInput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceActionInput) ProtoMessage() {}

func (x *AdminResourceActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceActionInput.ProtoReflect.Descriptor instead.
func (*AdminResourceActionInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminResourceActionInput) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *AdminResourceActionInput) GetContributionId() string {
	if x != nil {
		return x.ContributionId
	}
	return ""
}

func (x *AdminResourceActionInput) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AdminResourceActionInput) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AdminResourceActionInput) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AdminResourceActionInput) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *AdminResourceActionInput) GetAuthzChecked() bool {
	if x != nil {
		return x.AuthzChecked
	}
	return false
}

func (x *AdminResourceActionInput) GetAuthzAllowed() bool {
	if x != nil {
		return x.AuthzAllowed
	}
	return false
}

func (x *AdminResourceActionInput) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AdminActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActionResult) Reset() {
	*x = AdminActionResult{}
	mi := &file_internal_contracts_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionResult) ProtoMessage() {}

func (x *AdminActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionResult.ProtoReflect.Descriptor instead.
func (*AdminActionResult) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminActionResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AdminActionResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminActionResult) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *AdminActionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminResourceActionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *AdminActionResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResourceActionOutput) Reset() {
	*x = AdminResourceActionOutput{}
	mi := &file_internal_contracts_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceActionOutput) ProtoMessage() {}

func (x *AdminResourceActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceActionOutput.ProtoReflect.Descriptor instead.
func (*AdminResourceActionOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminResourceActionOutput) GetResult() *AdminActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AdminResourceActionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_admin_proto protoreflect.FileDescriptor

const file_internal_contracts_admin_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/admin.proto\x12\x19workflow.plugins.admin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xea\x01\n" +
	"\x14AdminDashboardConfig\x12!\n" +
	"\froute_prefix\x18\x01 \x01(\tR\vroutePrefix\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"target_app\x18\x03 \x01(\tR\ttargetApp\x12\x1f\n" +
	"\vauth_module\x18\x04 \x01(\tR\n" +
	"authModule\x12!\n" +
	"\fauthz_module\x18\x05 \x01(\tR\vauthzModule\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"asset_root\x18\a \x01(\tR\tassetRoot\")\n" +
	"\x0fAdminStepConfig\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\"e\n" +
	"\x0fAdminPermission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"\xf6\x01\n" +
	"\x14AdminContextSelector\x120\n" +
	"\x14selected_context_key\x18\x01 \x01(\tR\x12selectedContextKey\x122\n" +
	"\x15allowed_context_kinds\x18\x02 \x03(\tR\x13allowedContextKinds\x12\x1d\n" +
	"\n" +
	"launch_url\x18\x03 \x01(\tR\tlaunchUrl\x12Y\n" +
	"\x12switch_permissions\x18\x04 \x03(\v2*.workflow.plugins.admin.v1.AdminPermissionR\x11switchPermissions\"\xa4\x03\n" +
	"\x11AdminContribution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vrender_mode\x18\x05 \x01(\tR\n" +
	"renderMode\x12\x1f\n" +
	"\vapp_context\x18\x06 \x01(\tR\n" +
	"appContext\x12L\n" +
	"\vpermissions\x18\a \x03(\v2*.workflow.plugins.admin.v1.AdminPermissionR\vpermissions\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x18\n" +
	"\aactions\x18\t \x03(\tR\aactions\x12Z\n" +
	"\x10context_selector\x18\n" +
	" \x01(\v2/.workflow.plugins.admin.v1.AdminContextSelectorR\x0fcontextSelector\"\x85\x01\n" +
	"\x19RegisterContributionInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12P\n" +
	"\fcontribution\x18\x02 \x01(\v2,.workflow.plugins.admin.v1.AdminContributionR\fcontribution\"\xa4\x01\n" +
	"\x1aRegisterContributionOutput\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered\x12P\n" +
	"\fcontribution\x18\x02 \x01(\v2,.workflow.plugins.admin.v1.AdminContributionR\fcontribution\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x95\x02\n" +
	"\x16ListContributionsInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1f\n" +
	"\vapp_context\x18\x02 \x01(\tR\n" +
	"appContext\x12/\n" +
	"\x13granted_permissions\x18\x03 \x03(\tR\x12grantedPermissions\x122\n" +
	"\x15selected_context_kind\x18\x04 \x01(\tR\x13selectedContextKind\x12.\n" +
	"\x13selected_context_id\x18\x05 \x01(\tR\x11selectedContextId\x12-\n" +
	"\x12context_authorized\x18\x06 \x01(\bR\x11contextAuthorized\"\x83\x01\n" +
	"\x17ListContributionsOutput\x12R\n" +
	"\rcontributions\x18\x01 \x03(\v2,.workflow.plugins.admin.v1.AdminContributionR\rcontributions\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x9d\x02\n" +
	"\x19AuthorizeAdminActionInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vapp_context\x18\x05 \x01(\tR\n" +
	"appContext\x12#\n" +
	"\rauthz_checked\x18\x06 \x01(\bR\fauthzChecked\x12#\n" +
	"\rauthz_allowed\x18\a \x01(\bR\fauthzAllowed\x12/\n" +
	"\x13granted_permissions\x18\b \x03(\tR\x12grantedPermissions\"\xb2\x01\n" +
	"\x1aAuthorizeAdminActionOutput\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\xc7\x02\n" +
	"\x18AdminResourceActionInput\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12'\n" +
	"\x0fcontribution_id\x18\x02 \x01(\tR\x0econtributionId\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1f\n" +
	"\vapp_context\x18\x06 \x01(\tR\n" +
	"appContext\x12#\n" +
	"\rauthz_checked\x18\a \x01(\bR\fauthzChecked\x12#\n" +
	"\rauthz_allowed\x18\b \x01(\bR\fauthzAllowed\x121\n" +
	"\apayload\x18\t \x01(\v2\x17.google.protobuf.StructR\apayload\"\x8e\x01\n" +
	"\x11AdminActionResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x06output\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"w\n" +
	"\x19AdminResourceActionOutput\x12D\n" +
	"\x06result\x18\x01 \x01(\v2,.workflow.plugins.admin.v1.AdminActionResultR\x06result\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBAZ?github.com/GoCodeAlone/workflow-plugin-admin/internal/contractsb\x06proto3"

var (
	file_internal_contracts_admin_proto_rawDescOnce sync.Once
	file_internal_contracts_admin_proto_rawDescData []byte
)

func file_internal_contracts_admin_proto_rawDescGZIP() []byte {
	file_internal_contracts_admin_proto_rawDescOnce.Do(func() {
		file_internal_contracts_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_admin_proto_rawDesc), len(file_internal_contracts_admin_proto_rawDesc)))
	})
	return file_internal_contracts_admin_proto_rawDescData
}

var file_internal_contracts_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_contracts_admin_proto_goTypes = []any{
	(*AdminDashboardConfig)(nil),       // 0: workflow.plugins.admin.v1.AdminDashboardConfig
	(*AdminStepConfig)(nil),            // 1: workflow.plugins.admin.v1.AdminStepConfig
	(*AdminPermission)(nil),            // 2: workflow.plugins.admin.v1.AdminPermission
	(*AdminContextSelector)(nil),       // 3: workflow.plugins.admin.v1.AdminContextSelector
	(*AdminContribution)(nil),          // 4: workflow.plugins.admin.v1.AdminContribution
	(*RegisterContributionInput)(nil),  // 5: workflow.plugins.admin.v1.RegisterContributionInput
	(*RegisterContributionOutput)(nil), // 6: workflow.plugins.admin.v1.RegisterContributionOutput
	(*ListContributionsInput)(nil),     // 7: workflow.plugins.admin.v1.ListContributionsInput
	(*ListContributionsOutput)(nil),    // 8: workflow.plugins.admin.v1.ListContributionsOutput
	(*AuthorizeAdminActionInput)(nil),  // 9: workflow.plugins.admin.v1.AuthorizeAdminActionInput
	(*AuthorizeAdminActionOutput)(nil), // 10: workflow.plugins.admin.v1.AuthorizeAdminActionOutput
	(*AdminResourceActionInput)(nil),   // 11: workflow.plugins.admin.v1.AdminResourceActionInput
	(*AdminActionResult)(nil),          // 12: workflow.plugins.admin.v1.AdminActionResult
	(*AdminResourceActionOutput)(nil),  // 13: workflow.plugins.admin.v1.AdminResourceActionOutput
	(*structpb.Struct)(nil),            // 14: google.protobuf.Struct
}
var file_internal_contracts_admin_proto_depIdxs = []int32{
	2,  // 0: workflow.plugins.admin.v1.AdminContextSelector.switch_permissions:type_name -> workflow.plugins.admin.v1.AdminPermission
	2,  // 1: workflow.plugins.admin.v1.AdminContribution.permissions:type_name -> workflow.plugins.admin.v1.AdminPermission
	14, // 2: workflow.plugins.admin.v1.AdminContribution.metadata:type_name -> google.protobuf.Struct
	3,  // 3: workflow.plugins.admin.v1.AdminContribution.context_selector:type_name -> workflow.plugins.admin.v1.AdminContextSelector
	4,  // 4: workflow.plugins.admin.v1.RegisterContributionInput.contribution:type_name -> workflow.plugins.admin.v1.AdminContribution
	4,  // 5: workflow.plugins.admin.v1.RegisterContributionOutput.contribution:type_name -> workflow.plugins.admin.v1.AdminContribution
	4,  // 6: workflow.plugins.admin.v1.ListContributionsOutput.contributions:type_name -> workflow.plugins.admin.v1.AdminContribution
	14, // 7: workflow.plugins.admin.v1.AdminResourceActionInput.payload:type_name -> google.protobuf.Struct
	14, // 8: workflow.plugins.admin.v1.AdminActionResult.output:type_name -> google.protobuf.Struct
	12, // 9: workflow.plugins.admin.v1.AdminResourceActionOutput.result:type_name -> workflow.plugins.admin.v1.AdminActionResult
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_contracts_admin_proto_init() }
func file_internal_contracts_admin_proto_init() {
	if File_internal_contracts_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_admin_proto_rawDesc), len(file_internal_contracts_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_admin_proto_goTypes,
		DependencyIndexes: file_internal_contracts_admin_proto_depIdxs,
		MessageInfos:      file_internal_contracts_admin_proto_msgTypes,
	}.Build()
	File_internal_contracts_admin_proto = out.File
	file_internal_contracts_admin_proto_goTypes = nil
	file_internal_contracts_admin_proto_depIdxs = nil
}
